### ISSUE TITLE
Solcast have discontinued tuning from hobbyists

### ISSUE THREAD

**Issue by B-Hartley** [dannerph/homeassistant-solcast#12]
Looks like the upload functionality is now redundant.....

Thanks for using the API Toolkit! We wanted to let you know that we have decommissioned PV Tuning for hobbyist users.
You will no longer be able to POST PV measurements to the Solcast API. However, we are offering you the capability to add a 2nd rooftop site to your account. This 2nd site must be at the same location, and is only meant to help you accurately forecast for split array systems. 
Simply reply to this message if you'd like to access your 2nd site for free. 
Happy solar forecasting!

**Comment by jmftang86** [comment]
Hi, would you be able to add a second rooftop site to my account please? 16f2-75cb-0087-cc62

**Comment by B-Hartley** [comment]
I think you need to contact Solcast to request that. Sorry if I confused by pasting the advice message in here. 
xontact then through the support link on their site.

**Comment by jmftang86** [comment]
Ah yes thanks. just realised you copied and pasted their message 😂

I have deleted my message with he site code. 

I have been trying to integrate your solcast integration but having difficulty. 
it is not showing up on HACS as a searchable one. I have manage to use the url to add it and also tried downloading and pasting content to the customs component file which gave me the entities for solcast but I can only graphically show the history and not the forecast. (returns as unknown or non numeric) 

Do you know what might be going on? I am quite new to HA and scripting so sorry if it is a really silly step I missed.

**Comment by dannerph** [comment]
> I have been trying to integrate your solcast integration but having difficulty.
> it is not showing up on HACS as a searchable one. I have manage to use the url to add it and also tried downloading and pasting content to the customs component file which gave me the entities for solcast but I can only graphically show the history and not the forecast. (returns as unknown or non numeric)

For now, I have not added the component to HACS or home assistant directly, as it is not ready (feature and documentation-wise) as you already found out ;)

The recorder component in home assistant can only handle past values, thus there is no option to visualize future events, as far as I know. That is why I decided to make the future values useable for automation (check the forecast sensor). If you want to look at beautiful graphs, just login to solcast. We do not want to reimplement stuff, but make it interoperable with our local energy devices.

**Comment by jmftang86** [comment]
Thanks Philipp! That explains alot! 

What I actually want to have on my HA dashboard is not the standard graphs from the Solcast website but the total energy I am predicted to produce in kWh for today and the next as a graphic display.

Would you mind giving me some pointers to how I can make this happen? I have not yet explored automation function yet (I went from completely HA naive to setting a virtual machine on WIndows, installing HA OS, and HACS integration in one day's work with no experience of coding, so please do bear with me :))

Joe

**Comment by B-Hartley** [comment]
You could maybe use Apex Charts component to create a custom graph.
I'll have a play and see what I can do, I haven't used it yet.
So you are looking for a bar chart of today, tomorrow, day after (total production) ?

**Comment by jmftang86** [comment]
Yes, it's so I can decide whether or not to charge my batteries up/ how low I should run it down to for solar to be stored :)

**Comment by dannerph** [comment]
Regarding the initial issue, I will leave the code for pushing measurements in case some user has a paid subscription.

**Comment by B-Hartley** [comment]
Not sure when they are actually stopping the tuning, but my account is tuning still almost daily.
Also, I seem to have 50 API credits a day and two rooftops !

So OK for now at least, if the tuning stops, then I'll have to split to two rooftops and estimate it.
