### ISSUE TITLE
Timezone question (UTC vs DST)

### ISSUE THREAD

**Issue by monkeydust** [dannerph/homeassistant-solcast#15]
Just realised that solcast history data is in UTC whereas my solar data is in DST (right now here in UK). How do people handle the difference when recording to the DB? Txs

**Comment by dannerph** [comment]
Hi @monkeydust 
home assistant internally uses UTC in all parts as far as I know, thus recording to the database should be UTC as well (see [recorder](https://www.home-assistant.io/integrations/recorder/) or [influxdb ](https://www.home-assistant.io/integrations/influxdb/) integration). If you refer to pushing measurements to solcast, it is a matter of correct preprocessing of your data. In case the data source is from within home assistant, it should already be UTC?

**Comment by monkeydust** [comment]
got it, thank you
