### ISSUE TITLE
Home Assistant - Version Requirement

### ISSUE THREAD

**Issue by headbouyJB** [dannerph/homeassistant-solcast#18]
From 2021.6, Home Assistant now requires custom components to have a valid version noted. 

Since updating to this Home Assistant build, it no longer recognises 'solcast' as a valid integration :-( 

Can you please add versioning to 'solcast' so it will continue working with Home Assistant?

https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/#versions

**Comment by dannerph** [comment]
Version number has already been added. Please update to latest release (0.2.5).

There was a pre-release with wrong version number, which I have cleaned up now.
