### ISSUE TITLE
hassio 0.117 breaking change

### ISSUE THREAD

**Issue by pops106** [dannerph/homeassistant-solcast#2]
Hello, I have updated to the latest hassio which appears to have broken the solcast integration.

I get this error: Coroutine not allowed to be passed to HassJob

It looks to be related to this change introduced: https://github.com/home-assistant/core/pull/42073

Cheers

**Comment by dannerph** [comment]
should be fixed now. I also merged the additional, optional configs to disable automatic forecast fetching at midnight (you can create an automation and call the update_forecast service call) and set your API limit, which is used for the historical data fetching.
