### ISSUE TITLE
Forecast integration with my current graph

### ISSUE THREAD

**Issue by BeyondPixels** [dannerph/homeassistant-solcast#4]
Hello,

First of all, thanks for you work.
I'm just starting with HA in general, so I apologize in advance for the beginner question here.

I'm currently using HA, InfluxDB and Grafana to render some graph the consumption of my EVSE and smartplugs as well as my solar production for the whole day. The end goal for me is to add another line with the solar forecast, including the adjustments it can make with new calls.

I already had a free SolCast account and got result through API calls from another device.
I cloned your repos., and added the documented config. in configuration.yml.
![image](https://user-images.githubusercontent.com/53296978/101183653-1571df80-3650-11eb-8576-657b4f4224e6.png)

So far, the Solcast history seems to work ok but not the forecast:
![image](https://user-images.githubusercontent.com/53296978/101183301-a09ea580-364f-11eb-830b-9dd8d4caedfd.png)

Any idea why?

**Comment by dannerph** [comment]
Hi there,
by default forecasts are fetched at your local midnight time for the next days. However, you can trigger the forecast fetching anytime using the corresponding home assistant service (keep your API limit in mind).

Currently I sum up the total expected energy production for the current day, the next day and the day after that. As HA does not provide any functionality to store prediction data, I have not distinguished between the different hours of the raw response of solcast but just summed it up to days.

BTW: I added the solcast component to HACS, so you might be interested in enhancing your HA installation with this community based "app store": https://hacs.xyz/docs/installation/prerequisites

BR
Philipp

**Comment by BeyondPixels** [comment]
Hi Philipp,

Thanks for your quick answer, the explanation and tips.
Too bad HA doesn't provide prediction data. Any idea if it can be done with InfluxDB?

**Comment by dannerph** [comment]
I guess it should be possible to create a separate app, that uses the Solcast API for fetching forecasting data and storing (overwriting) data in influxdb. However, that is not the intention of this integration.

If you don't mind, I would close this issue.
