### ISSUE TITLE
Error during startup 

### ISSUE THREAD

**Issue by elRadix** [dannerph/homeassistant-solcast#5]
Can you please how to resolve this error please? 

```
Logger: homeassistant.setup
Source: setup.py:138
First occurred: 4:22:38 PM (1 occurrences)
Last logged: 4:22:38 PM

Setup failed for solcast: Requirements for solcast not found: ['aiohttp==3.6.2'].

Logger: homeassistant.util.package
Source: util/package.py:95
First occurred: 4:22:38 PM (1 occurrences)
Last logged: 4:22:38 PM

Unable to install package aiohttp==3.6.2: ERROR: Could not find a version that satisfies the requirement aiohttp==3.6.2 ERROR: No matching distribution found for aiohttp==3.6.2
```

## System Health

version | 1.0.0b1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.6
os_name | Linux
os_version | 5.4.81
arch | x86_64
timezone | Europe/Brussels

**Comment by dannerph** [comment]
Which version of Home Assistant are you using? It might be related to the new dependency resolver within the newest verison of pip ( https://github.com/home-assistant/core/pull/43771).

Please update to version 0.118.5 and report back.

**Comment by elRadix** [comment]
If it will be fixed when 1.0 will be officially announced then I'll wait.

**Comment by dannerph** [comment]
Ah you are using the newest pre-release, I am still running 0.118.2 on my production system. Sorry I cannot give support for pre-releases.

**Comment by elRadix** [comment]
this error below persist using the current stable version released couple days ago 

System Health
Version	2020.12.1
Installation Type	Home Assistant OS
Development	false
Supervisor	true
Docker	true
Virtual Environment	false
Python Version	3.8.6
Operating System Family	Linux
Operating System Version	5.4.83
CPU Architecture	x86_64
```
Logger: homeassistant.util.package
Source: util/package.py:95
First occurred: 2:05:07 PM (1 occurrences)
Last logged: 2:05:07 PM

Unable to install package aiohttp==3.6.2: ERROR: Could not find a version that satisfies the requirement aiohttp==3.6.2 ERROR: No matching distribution found for aiohttp==3.6.2
```

**Comment by dannerph** [comment]
Mhm I cannot reproduce this error on my installation ... however, I am using the official homeassistant/core docker image not HassOS, which should actually use the same.

Could you try to replace ```aiohttp==3.6.2``` with ```aiohttp>=3.6.2``` in manifest.json and report back?

**Comment by elRadix** [comment]
that fixed the issue, thank you
maybe push a fix for that?

**Comment by dannerph** [comment]
done, thanks for testing
