### ISSUE TITLE
History attributes as template sensors

### ISSUE THREAD

**Issue by BeyondPixels** [dannerph/homeassistant-solcast#7]
Hello,

Sorry to bother you with this but I feel like a tried a millions ways and it doesn't work.

I'd like the values from "Tomorrow" and "The day after tomorrow" as sensors to be displayed in lovelace but I can't figure out how to do it.

Here is what I've written:
- platform: template
  sensors:
    solcast_history:
      friendly_name: "Previsions PV"
      unit_of_measurement: 'W'
      value_template: "{{ (states('sensor.solcast_history_2') | float * 1000) | round(0) }}"
      icon_template: mdi:solar-power
    solcast_forecast_tomorrow:
      friendly_name: "Solcast - Prévisions de demain"
      unit_of_measurement: "kWh"
(hashtag here)      value_template: "{{ state_attr('sensor.solcast_forecast_2','tomorrow') }}"
      value_template: {{ states.sensor.solcast_forecast_2.attributes.tomorrow }}
      icon_template: mdi:solar-power
    solcast_forecast_in2days:
      friendly_name: "Solcast - Prévisions dans 2 jours"
      unit_of_measurement: "kWh"
      value_template: "{{ state_attr('sensor.solcast_forecast_2','the day after tomorrow') }}"
      icon_template: mdi:solar-power

"value_template: {{ states.sensor.solcast_forecast_2.attributes.tomorrow }}" returns an error:
"invalid key: "OrderedDict([('states.sensor.solcast_forecast_2.attributes.Tomorrow', None)])" in "/config/sensors/sensors_solcast.yaml", line 12, column 0"

...And it displays "Unknown" on Lovelace.

"value_template: "{{ state_attr('sensor.solcast_forecast_2','Tomorrow') }}" doesn't return an error but still displays "Unknown" in Lovelace.

![image](https://user-images.githubusercontent.com/53296978/106108516-a644d300-6148-11eb-9918-1e410996cfcb.png)

![image](https://user-images.githubusercontent.com/53296978/106108450-91683f80-6148-11eb-8e3e-e57da66f1e85.png)

Any idea why?
Thanks in advance

**Comment by dannerph** [comment]
Hi there,

```{{ state_attr('sensor.solcast_forecast','tomorrow') }}``` and ```{{ state_attr('sensor.solcast_forecast','the day after tomorrow') }}``` is working for me. This is actually the way you should retrieve attribute values.

Your issue might be becuase you have bit letter of ```T``` insted of a small one?

You can try it using the template section of the [development tools](https://www.home-assistant.io/docs/tools/dev-tools/).
